# Generated by Django 5.0.1 on 2024-03-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0002_remove_buyer_user_remove_seller_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_price', models.CharField(max_length=255)),
                ('categories', models.CharField(choices=[('skincare', 'Skincare'), ('makeup', 'Makeup'), ('haircare', 'Haircare'), ('fragrances', 'Fragrances'), ('bodycare', 'Bodycare')], max_length=20)),
                ('description', models.TextField()),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='static/productimages/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
