# Generated by Django 5.0.1 on 2024-03-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/productimages'),
        ),
    ]
